services:
  auth-pg:
    container_name: auth-pg
    image: postgres
    volumes:
      - auth-pg:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: unless-stopped

  auth-app:
    container_name: auth-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
    env_file:
      - ./.env
    ports:
      - "8089:8089"
    depends_on:
      - auth-pg
    restart: unless-stopped

volumes:
  auth-pg: